# Install etcdctl
- name: Install etcdctl
  shell: |
    ETCD_VERSION="v{{ k3s_server_etcdctl_version }}"
    if [[ "$(uname -m)" = "aarch64" ]]
    then ETCD_ARCH="arm64"
    else ETCD_ARCH="amd64"
    fi
    ETCD_URL="https://github.com/etcd-io/etcd/releases/download/${ETCD_VERSION}/etcd-${ETCD_VERSION}-linux-${ETCD_ARCH}.tar.gz"
    curl -sL ${ETCD_URL} | sudo tar -zxv --strip-components=1 -C /usr/local/bin
  args:
    creates: /usr/local/bin/etcdctl
- name: Install k3s-etcdctl
  copy:
    src: "k3s-etcdctl.sh"
    dest: "/usr/local/bin/k3s-etcdctl"
    owner: root
    group: root
    mode: 0755

# Register and enable k3s service.
- name: Update K3s config
  template:
    src: "k3s.default.j2"
    dest: "/etc/default/k3s"
    owner: root
    group: root
    mode: 0640
  notify:
    - restart k3s
- name: Install K3s systemd service
  template:
    src: "k3s.service.j2"
    dest: "{{ systemd_dir }}/k3s.service"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart k3s
- name: Enable and check K3s service
  systemd:
    name: k3s
    daemon_reload: yes
    state: started
    enabled: yes
