# Register and enable k3s service.
- name: Update K3s config
  template:
    src: "k3s.default.j2"
    dest: "/etc/default/k3s"
    owner: root
    group: root
    mode: 0640
  notify:
    - restart k3s
- name: Install K3s systemd service
  template:
    src: "k3s.service.j2"
    dest: "{{ systemd_dir }}/k3s.service"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart k3s
- name: Enable and check K3s service
  systemd:
    name: k3s
    daemon_reload: yes
    state: started
    enabled: yes
