# Prerequisites and software download
- import_tasks: prereq.yml
- import_tasks: download.yml
- import_tasks: swapoff.yml
  tags: k3s-swapoff

# Installation
- import_tasks: preinstall.yml
  when: k3s_server or k3s_agent
- import_tasks: install-server.yml
  when: k3s_server
- import_tasks: install-agent.yml
  when: k3s_agent and not k3s_server
