- name: Find required mounts
  shell: |
    echo $(
      for d in /var/lib/rancher /var/lib/containers /var/lib/kubelet
      do systemctl list-units | grep -wo $d | awk '{ print $1 }'
      done | sort -u
    )
  register: k3s_required_mounts
- name: Set required mounts
  set_fact:
    k3s_mounts: "{{ k3s_required_mounts.stdout }}"
