# Disable swap
- name: disable fstab swap
  replace:
    path: /etc/fstab
    regexp: '^([^\s#][^\s]*[\s]+[^\s]+[\s]+swap[\s]+.*)$'
    replace: '#\1'
    backup: yes
- name: enumerate systemd swap units
  shell:
    cmd: "systemctl list-unit-files --type swap | grep -v ^UNIT | tr -s '[[:space:]]' | grep 'enabled$' | cut -d' ' -f 1"
  register: systemd_swap_units
  changed_when: no
  when: ansible_service_mgr | lower == 'systemd'
- name: mask systemd swap units
  shell:
    cmd: "systemctl mask {{ item }}"
  loop: "{{ systemd_swap_units.stdout_lines | map('trim') | list() }}"
  when: systemd_swap_units.stdout_lines | default([]) | length() > 0
- name: disable swap
  command: swapoff -a
  changed_when: no

# Override swappiness
- name: disable swappiness
  copy:
    content: |
      vm.swappiness=0
    dest: /etc/sysctl.d/51-kubernetes.conf
    mode: 0644
    owner: root
    group: root
  register: disable_swappiness
- name: apply swappiness
  shell: sysctl -p /etc/sysctl.d/51-kubernetes.conf
  when: disable_swappiness.changed
