# Disable swap
- name: disable fstab swap
  replace:
    path: /etc/fstab
    regexp: '^([^\s#][^\s]*[\s]+[^\s]+[\s]+swap[\s]+.*)$'
    replace: '#\1'
    backup: yes
- name: enumerate systemd swap unit files
  shell:
    cmd: "systemctl list-unit-files --type swap | grep -v ^UNIT | tr -s '[[:space:]]' | grep 'enabled$' | cut -d' ' -f 1"
  register: systemd_swap_unit_files
  changed_when: no
  when: ansible_service_mgr | lower == 'systemd'
- name: mask systemd swap unit files
  systemd_service:
    name: "{{ item }}"
    masked: true
  loop: "{{ systemd_swap_unit_files.stdout_lines | map('trim') | list() }}"
  when: systemd_swap_unit_files.stdout_lines | default([]) | length() > 0
- name: enumerate common systemd swap units
  shell:
    cmd: "systemctl list-units | sed -ne 's@^  \\(dphys-swapfile\\.service\\|.*\\.swap\\) .*$@\\1@p'"
  register: systemd_swap_units
  changed_when: no
  when: ansible_service_mgr | lower == 'systemd'
- name: mask systemd swap units
  systemd_service:
    name: "{{ item }}"
    masked: true
  loop: "{{ systemd_swap_units.stdout_lines | map('trim') | list() }}"
  when: systemd_swap_units.stdout_lines | default([]) | length() > 0
- name: mask systemd swap.target
  systemd_service:
    name: swap.target
    masked: true
- name: disable swap
  command: swapoff -a
  changed_when: no

# Override swappiness
# See:
# - https://kb.lc/01.how_to/kswapd0/
- name: remove default swappiness
  lineinfile:
    path: /etc/sysctl.conf
    state: absent
    regexp: '^vm.swappiness'
- name: disable swappiness
  copy:
    content: |
      vm.swappiness=0
    dest: /etc/sysctl.d/51-kubernetes.conf
    mode: 0644
    owner: root
    group: root
  register: disable_swappiness
- name: apply swappiness
  shell: sysctl -p /etc/sysctl.d/51-kubernetes.conf
  when: disable_swappiness.changed
