- name: restart k3s
  service:
    name: k3s
    state: "{{ 'restarted' if k3s_server else 'stopped' }}"
- name: restart k3s-agent
  service:
    name: k3s-agent
    state: "{{ 'restarted' if k3s_agent else 'stopped' }}"
